### ISSUE TITLE
PopUp window 

### ISSUE THREAD

**Issue by M0rrighan** [Akhtar-Joomun/portfolio#14]
Hi Akhtar, I can see you put great effort into this project and made a lot of progress. There are few improvements that you may want to consider. I noticed that the Title in the PopUp window loses the class 'worksHeadInfo' that is assigned to the Title in the Cards , maybe by adding it also the the modal Title it would look as in the template.

**Comment by Tchilo** [comment]
hi, Akhtar great work done here!

**Comment by Akhtar-Joomun** [comment]
Hi Radmila and Taro...
Thank you for your reviews. The title of the pop-up window has been modified to match the Figma requirement.
And the size of the pop-up window itself also has been corrected to fit the screen.
