### ISSUE TITLE
Akhtar Portfolio skeleton Issue

### ISSUE THREAD

**Issue by zieeco** [Akhtar-Joomun/portfolio#3]
## CONGRATULATION :clap: 

You've really done a great job on your project so far. keep up the good work. 

## Required changes

- Please add a live Demo of your project in your readme file
- Also, add a screenshot of your project in your readme file
-Please change your default branch to main and merge everything to that main branch

## Thanks 
Happy coding :clap: ......

**Comment by Akhtar-Joomun** [comment]
Live demo link has been added.
Screenshot has been fixed.
