### ISSUE TITLE
Desktop Portfolio issue

### ISSUE THREAD

**Issue by andersonlebon** [Akhtar-Joomun/portfolio#6]
## CONGRATULATIONS :clap: :clap:

you have done a great job  :+1: but here are something you may improve:
- [x] It would be better to make different sizes for the queries so that they may fit on the desktop version the way that it required in the specification of the project
- [x] I think your project may look better if you try to remove the horizontal scroll bar

HAPPY CODING!! :code:

**Comment by Akhtar-Joomun** [comment]
Thank you for the review, Anderson. 
I have made the changes that you asked for.

**Comment by andersonlebon** [comment]
okay!! thanks, I appreciate really it.
